INSERT INTO categories (`categorie`, `label`) VALUES('lacets',"Lacets");
INSERT INTO categories (`categorie`, `label`) VALUES('proteges',"Protège-Lames");
INSERT INTO categories (`categorie`, `label`) VALUES('patins',"Patins");
INSERT INTO produits VALUES('La1','src="./img/produits/lacets/lacet1.png" alt="Lacets jaunes"',9,'Lacets jaunes',6.99,"lacets");
INSERT INTO produits VALUES('La2','src="./img/produits/lacets/lacet2.png" alt="Lacets bleus"',8,'Lacets bleus',6.99,"lacets");
INSERT INTO produits VALUES('La3','src="./img/produits/lacets/lacet3.png" alt="Lacets verts"',7,'Lacets verts',6.99,"lacets");
INSERT INTO produits VALUES('La4','src="./img/produits/lacets/lacet4.png" alt="Lacets rouges"',6,'Lacets rouges',6.99,"lacets");
INSERT INTO produits VALUES('La5','src="./img/produits/lacets/lacet5.png" alt="Lacets roses"',5,'Lacets roses',6.99,"lacets");
INSERT INTO produits VALUES('Pr1','src="./img/produits/proteges/protege1.png" alt="Protège-lames verts"',9,'Protège-lames verts',9.99,"proteges");
INSERT INTO produits VALUES('Pr2','src="./img/produits/proteges/protege2.png" alt="Protège-lames jaunes"',8,'Protège-lames jaunes',9.99,"proteges");
INSERT INTO produits VALUES('Pr3','src="./img/produits/proteges/protege3.png" alt="Protège-lames bleus"',7,'Protège-lames bleus',9.99,"proteges");
INSERT INTO produits VALUES('Pr4','src="./img/produits/proteges/protege4.png" alt="Protège-lames blancs"',6,'Protège-lames blancs',9.99,"proteges");
INSERT INTO produits VALUES('Pr5','src="./img/produits/proteges/protege5.png" alt="Protège-lames roses"',5,'Protège-lames roses',9.99,"proteges");
INSERT INTO produits VALUES('Pa1','src="./img/produits/patins/patin1.png" alt="Patins motifs jaunes"',5,'Patins motifs jaunes',34.99,"patins");
INSERT INTO produits VALUES('Pa2','src="./img/produits/patins/patin2.png" alt="Patins motifs gris"',4,'Patins motifs gris',34.99,"patins");
INSERT INTO produits VALUES('Pa3','src="./img/produits/patins/patin3.png" alt="Patins à fourrure"',3,'Patins à fourrure',42.99,"patins");
INSERT INTO produits VALUES('Pa4','src="./img/produits/patins/patin4.png" alt="Patins classiques"',2,'Patins classiques',40.99,"patins");
INSERT INTO produits VALUES('Pa5','src="./img/produits/patins/patin5.png" alt="Patins motif bleu"',1,'Patins motif bleu',44.99,"patins");